// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Entities.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20211026184433_InitialData")]
    partial class InitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("Entities.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Address Id");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AddressId");

                    b.HasIndex("StudentId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            AddressId = 1,
                            City = "London",
                            Country = "UK",
                            Street = "Frying Pan Road",
                            StudentId = 1
                        },
                        new
                        {
                            AddressId = 2,
                            City = "Cincinnati",
                            Country = "USA",
                            Street = "Error Place",
                            StudentId = 2
                        },
                        new
                        {
                            AddressId = 3,
                            City = "Rome",
                            Country = "Italy",
                            Street = "Bad Route Road",
                            StudentId = 3
                        },
                        new
                        {
                            AddressId = 4,
                            City = "Las Vegas",
                            Country = "USA",
                            Street = "Pillow Talk Court",
                            StudentId = 4
                        },
                        new
                        {
                            AddressId = 5,
                            City = "Berlin",
                            Country = "Germany",
                            Street = "This Street",
                            StudentId = 5
                        });
                });

            modelBuilder.Entity("Entities.Models.Exam", b =>
                {
                    b.Property<int>("examId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Exam Id");

                    b.Property<decimal>("Credits")
                        .HasColumnType("decimal(4)")
                        .HasColumnName("Credits");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfessorName")
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("examId");

                    b.HasIndex("StudentId");

                    b.ToTable("Exams");

                    b.HasData(
                        new
                        {
                            examId = 1,
                            Credits = 6m,
                            Name = "Computer Programming",
                            ProfessorName = "Nicoline Abspoel",
                            StudentId = 1
                        },
                        new
                        {
                            examId = 2,
                            Credits = 5m,
                            Name = "Computer Architecture",
                            ProfessorName = "Ashlynn Van Hautum",
                            StudentId = 2
                        },
                        new
                        {
                            examId = 3,
                            Credits = 5.5m,
                            Name = "Databases",
                            ProfessorName = "Andrew Kennard",
                            StudentId = 3
                        },
                        new
                        {
                            examId = 4,
                            Credits = 5m,
                            Name = "Discrete Mathematics",
                            ProfessorName = "Algernon Aarse",
                            StudentId = 4
                        },
                        new
                        {
                            examId = 5,
                            Credits = 5m,
                            Name = "Data Structures and Algorithms",
                            ProfessorName = "Sampson Daelmans",
                            StudentId = 4
                        },
                        new
                        {
                            examId = 6,
                            Credits = 5.5m,
                            Name = "Operating Systems",
                            ProfessorName = "Ermintrude Royceston",
                            StudentId = 5
                        });
                });

            modelBuilder.Entity("Entities.Models.Student", b =>
                {
                    b.Property<int>("studentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("student Id");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime")
                        .HasColumnName("Date of Birth");

                    b.Property<DateTime?>("EnrollmentDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Enrollment Date");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("First Name");

                    b.Property<decimal?>("GPA")
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("GPA");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Last Name");

                    b.Property<string>("Mail")
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentIndex")
                        .HasColumnType("char(4)")
                        .HasColumnName("Student Index");

                    b.HasKey("studentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            studentId = 1,
                            EnrollmentDate = new DateTime(2018, 10, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            FirstName = "Kassidy",
                            LastName = "Trueman",
                            Mail = "Kassidy.Trueman@mail.com",
                            StudentIndex = "3516"
                        },
                        new
                        {
                            studentId = 2,
                            EnrollmentDate = new DateTime(2017, 10, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            FirstName = "Christobel",
                            LastName = "Bezuidenhout",
                            Mail = "Christobel.Bezuidenhout@mail.com",
                            StudentIndex = "1241"
                        },
                        new
                        {
                            studentId = 3,
                            EnrollmentDate = new DateTime(2019, 10, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            FirstName = "Kristel",
                            LastName = "Madison",
                            Mail = "Kristel.Madison@mail.com",
                            StudentIndex = "3121"
                        },
                        new
                        {
                            studentId = 4,
                            EnrollmentDate = new DateTime(2020, 10, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            FirstName = "Lyndsey",
                            LastName = "Albers",
                            Mail = "Lyndsey.Albers@mail.com",
                            StudentIndex = "1415"
                        },
                        new
                        {
                            studentId = 5,
                            EnrollmentDate = new DateTime(2018, 10, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            FirstName = "Alishia",
                            LastName = "Gabriels",
                            Mail = "Alishia.Gabriels@mail.com",
                            StudentIndex = "3717"
                        });
                });

            modelBuilder.Entity("Entities.Models.Transcript", b =>
                {
                    b.Property<int>("transcriptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Transcript Id");

                    b.Property<int>("ExamId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Points")
                        .HasColumnType("decimal(4)")
                        .HasColumnName("Points");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("transcriptId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("transcriptId");

                    b.HasIndex("ExamId");

                    b.HasIndex("StudentId");

                    b.HasIndex("transcriptId1");

                    b.ToTable("Transcripts");

                    b.HasData(
                        new
                        {
                            transcriptId = 1,
                            ExamId = 1,
                            Points = 90m,
                            StudentId = 1
                        },
                        new
                        {
                            transcriptId = 3,
                            ExamId = 5,
                            Points = 88m,
                            StudentId = 1
                        },
                        new
                        {
                            transcriptId = 2,
                            ExamId = 2,
                            Points = 65m,
                            StudentId = 3
                        },
                        new
                        {
                            transcriptId = 4,
                            ExamId = 2,
                            Points = 75m,
                            StudentId = 1
                        },
                        new
                        {
                            transcriptId = 6,
                            ExamId = 1,
                            Points = 81m,
                            StudentId = 2
                        },
                        new
                        {
                            transcriptId = 7,
                            ExamId = 3,
                            Points = 75.5m,
                            StudentId = 2
                        },
                        new
                        {
                            transcriptId = 8,
                            ExamId = 6,
                            Points = 98m,
                            StudentId = 2
                        },
                        new
                        {
                            transcriptId = 9,
                            ExamId = 5,
                            Points = 61m,
                            StudentId = 2
                        },
                        new
                        {
                            transcriptId = 10,
                            ExamId = 2,
                            Points = 65m,
                            StudentId = 3
                        },
                        new
                        {
                            transcriptId = 11,
                            ExamId = 1,
                            Points = 79m,
                            StudentId = 3
                        },
                        new
                        {
                            transcriptId = 12,
                            ExamId = 6,
                            Points = 67m,
                            StudentId = 3
                        },
                        new
                        {
                            transcriptId = 13,
                            ExamId = 1,
                            Points = 96m,
                            StudentId = 4
                        },
                        new
                        {
                            transcriptId = 14,
                            ExamId = 2,
                            Points = 89m,
                            StudentId = 4
                        },
                        new
                        {
                            transcriptId = 15,
                            ExamId = 3,
                            Points = 78m,
                            StudentId = 4
                        },
                        new
                        {
                            transcriptId = 16,
                            ExamId = 4,
                            Points = 94m,
                            StudentId = 4
                        },
                        new
                        {
                            transcriptId = 17,
                            ExamId = 5,
                            Points = 91m,
                            StudentId = 4
                        },
                        new
                        {
                            transcriptId = 18,
                            ExamId = 6,
                            Points = 82m,
                            StudentId = 4
                        },
                        new
                        {
                            transcriptId = 19,
                            ExamId = 3,
                            Points = 83m,
                            StudentId = 5
                        },
                        new
                        {
                            transcriptId = 20,
                            ExamId = 6,
                            Points = 78m,
                            StudentId = 5
                        },
                        new
                        {
                            transcriptId = 21,
                            ExamId = 5,
                            Points = 84m,
                            StudentId = 5
                        },
                        new
                        {
                            transcriptId = 22,
                            ExamId = 2,
                            Points = 69m,
                            StudentId = 5
                        });
                });

            modelBuilder.Entity("Entities.Models.Address", b =>
                {
                    b.HasOne("Entities.Models.Student", "Student")
                        .WithMany("Addresses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Entities.Models.Exam", b =>
                {
                    b.HasOne("Entities.Models.Student", "Student")
                        .WithMany("Exams")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Entities.Models.Transcript", b =>
                {
                    b.HasOne("Entities.Models.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Student", "Student")
                        .WithMany("Transcripts")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Transcript", null)
                        .WithMany("Transcripts")
                        .HasForeignKey("transcriptId1");

                    b.Navigation("Exam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Entities.Models.Student", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Exams");

                    b.Navigation("Transcripts");
                });

            modelBuilder.Entity("Entities.Models.Transcript", b =>
                {
                    b.Navigation("Transcripts");
                });
#pragma warning restore 612, 618
        }
    }
}
